DROP TABLE PATIENTS;
DROP TABLE DISEASES;
DROP TABLE DISEASE_SYMPTOMS;
DROP TABLE SYMPTOMS;

CREATE TABLE PATIENTS (
    PATIENT_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(30),
    AGE INTEGER,
    DISEASE_ID INTEGER
);
CREATE TABLE DISEASES (
    DISEASE_ID INTEGER PRIMARY KEY,
    DISEASE_NAME VARCHAR2(30),
    DISEASE_DESCRIPTION VARCHAR2(100)
);
CREATE TABLE DISEASE_SYMPTOMS (
    DISEASE_ID INTEGER,
    SYMPTOM_ID INTEGER
);
CREATE TABLE SYMPTOMS (
    SYMPTOM_ID INTEGER PRIMARY KEY,
    SYMPTOM_NAME VARCHAR2(40),
    SYMPTOM_DESCRIPTION VARCHAR2(100),
    IS_OBSERVABLE VARCHAR2(10),
    IS_TESTABLE VARCHAR2(10),
    SYMPTOM_TEST VARCHAR2(40)
);

ALTER TABLE PATIENTS
ADD CONSTRAINT FK_DISEASE_ID
FOREIGN KEY (DISEASE_ID) REFERENCES DISEASES(DISEASE_ID);

ALTER TABLE DISEASE_SYMPTOMS
ADD CONSTRAINT FK_DISEASE_SYMPTOMS_DISEASE_ID
FOREIGN KEY (DISEASE_ID) REFERENCES DISEASES(DISEASE_ID);

ALTER TABLE DISEASE_SYMPTOMS
ADD CONSTRAINT FK_DISEASE_SYMPTOMS_SYMPTOM_ID
FOREIGN KEY (SYMPTOM_ID) REFERENCES SYMPTOMS(SYMPTOM_ID);

INSERT ALL
INTO SYMPTOMS
VALUES(1,'Frequent Urination','Patient is urinating very often','yes','no',null)
INTO SYMPTOMS
VALUES(2,'Blurred Vision', 'Patient may not be able to see as well as they normally do','no','yes','Reading Test')
INTO SYMPTOMS
VALUES(3,'High Blood Sugar','Glucose levels in the blood are much higher than average','no','yes','Blood Test')
SELECT * FROM DUAL;

INSERT ALL
INTO DISEASES
VALUES(1,'Diabetes','A blood disease that restricts the breakdown of glucose')
INTO DISEASES
VALUES(2,'Laryngitis', 'Swelling and inflamation of the larynx')
INTO DISEASES
VALUES(3,'Fibromyalgia','Musculoskeletal disorder affecting neurons in the brain')
SELECT * FROM DUAL;

INSERT ALL
INTO DISEASE_SYMPTOMS
VALUES(1,1)
INTO DISEASE_SYMPTOMS
VALUES(1,2)
INTO DISEASE_SYMPTOMS
VALUES(1,3)
SELECT * FROM DUAL;

INSERT ALL
INTO PATIENTS
VALUES(1,'Hannah','Smith',46,1)
INTO PATIENTS
VALUES(2,'Joe', 'Beach',17,2)
INTO PATIENTS
VALUES(3,'Alex','Sanchez',82,3)
SELECT * FROM DUAL;

ALTER TABLE LEADERBOARD
ADD CONSTRAINT FK_LEADERBOARD_USER_ID
FOREIGN KEY (USER_ID) REFERENCES PLAYER(EMAIL);
